### ISSUE TITLE
Where examples for all style classes?

### ISSUE THREAD

**Issue by wterh** [StartBootstrap/startbootstrap-sb-admin-2#344]
I see other css style features, toast, tooltip, popover, carousel, but i not see one examples!

**Comment by aleckrh** [comment]
Hello, this template is based on Bootstrap 4. If you want to see some examples of popover, carousel, etc., check the Bootstrap documentation. Best luck!

**Comment by wterh** [comment]
> Hello, this template is based on Bootstrap 4. If you want to see some examples of popover, carousel, etc., check the Bootstrap documentation. Best luck!

I'm waiting for examples on the layout style sb2, not bootstrap examples.

**Comment by Schokobecher** [comment]
Good luck waiting then :)

**Comment by davidtmiller** [comment]
Anything that has been modified past the Bootstrap framework has been documented in the theme for the most part, but everything in the Bootstrap docs will get slightly restyled due to some global variable changes. For sake of brevity, I don't plan on re-stating everything in the Bootstrap docs within the theme, only things that are custom built exclusive to the theme or things that have been significantly changed. Hopefully this helps explain things!
